DROP TABLE IF EXISTS admins CASCADE;
DROP TABLE IF EXISTS menus CASCADE; 
DROP TABLE IF EXISTS beers CASCADE;

CREATE TABLE admins (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL,
  password_hash TEXT NOT NULL
);

CREATE TABLE menus (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  admin_id BIGINT REFERENCES admins(id),
  item TEXT NOT NULL,
  detail TEXT,
  price TEXT NOT NULL
);

CREATE TABLE beers (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  admin_id BIGINT REFERENCES admins(id),
  brewery TEXT NOT NULL,
  style TEXT NOT NULL,
  abv TEXT NOT NULL, 
  price TEXT NOT NULL
)
