DROP TABLE IF EXISTS menus CASCADE; 
DROP TABLE IF EXISTS beers CASCADE;

CREATE TABLE menus (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  item TEXT NOT NULL,
  detail TEXT,
  price TEXT NOT NULL
);

CREATE TABLE beers (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  brewery TEXT NOT NULL,
  style TEXT NOT NULL,
  abv TEXT NOT NULL, 
  price TEXT NOT NULL
)
